/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

export function Hole(props) {
  const { nodes, materials } = useGLTF('/newhole.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
      />
    </group>
  );
}

useGLTF.preload('/newhole.glb');
