/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { GroupProps, useFrame } from '@react-three/fiber';
import { useGLTF } from '@react-three/drei';

export function Machine(props) {
  const { nodes, materials } = useGLTF('/machine.glb');

  const group = useRef();

  return (
    <group
      {...props}
      dispose={null}
      rotation={[0, Math.PI / 2, 0]}
      position={[0, 0.5, -47]}
      ref={group}
    >
      <mesh
        geometry={nodes.machin1_low.geometry}
        material={materials.lambert1}
        rotation={[Math.PI / 2, 0, 0]}
        scale={2.25}
      />
      <mesh
        geometry={nodes.machin2_low.geometry}
        material={materials.lambert1}
        rotation={[Math.PI / 2, 0, 0]}
        scale={2.25}
      />
      <mesh
        geometry={nodes.machin3_low.geometry}
        material={materials.lambert1}
        rotation={[Math.PI / 2, 0, 0]}
        scale={2.25}
      />
      <mesh
        geometry={nodes.machin4_low.geometry}
        material={materials.lambert1}
        rotation={[Math.PI / 2, 0, 0]}
        scale={2.25}
      />
    </group>
  );
}

useGLTF.preload('/machine.glb');
